function sys=sh_plot_geometry_PSHA(ax3,sys,opt,indegeom,indsource)

if nargin==3
delete(findall(ax3,'type','line'));
delete(findall(ax3,'type','patch'));
delete(findall(ax3,'type','text'));
end

meshcolor  = [0.6 0.6 1];
edgecolor  = [1 0.6 0.6];
ae         = opt.ae;

if nargin==3
    Ngeom    = numel(sys.source);
    indegeom = 1:Ngeom;
end

%% plot area and volumen sources
for i=indegeom
    source  = sys.source{i};
    Nsource = numel(source);
    
    if nargin==3
        indsource=1:Nsource;
    end
    
    %% source depth
    dep     = sprintf('dept%g' ,i);
    for j=indsource
        sourcetype=round(source{j}.sourcetype);        
        if sourcetype==3
            gpsm = xyz2gps(source{j}.xyzm, ae);
            sys.source{i}{j}.handle_depth=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',source{j}.conn,...
                'facevertexcdata',gpsm(:,3),...
                'facecol','interp',...
                'edgecolor','none',...
                'tag',dep,...
                'visible','off',...
                'facealpha',0.75);
        end        
        if sourcetype==4
            gpsm = xyz2gps(source{j}.xyzm, ae);
            sys.source{i}{j}.handle_depth=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',source{j}.conn,...
                'facevertexcdata',gpsm(:,3),...
                'facecol','interp',...
                'edgecolor','none',...
                'tag',dep,...
                'visible','off',...
                'facealpha',0.75);
        end        
        if sourcetype==5
            t  = source{j}.conn;
            t2 = [t(:,[1 2 3]);t(:,[1 4 3]);t(:,[2 3 4]);t(:,[1 2 4])];
            t2 = unique(sort(t2,2),'rows');
            gpsm = xyz2gps(source{j}.xyzm, ae);
            sys.source{i}{j}.handle_depth=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',t2,...
                'facevertexcdata',gpsm(:,3),...
                'facecol','interp',...
                'edgecolor','none',...
                'tag',dep,...
                'visible','off',...
                'facealpha',0.75);
        end        
    end
    
    %% source mesh
    tag = sprintf('mesh%g' ,i);
    for j=indsource
        sourcetype=round(source{j}.sourcetype);        
        if sourcetype==2
            gpsm = xyz2gps(source{j}.xyzm, ae);
            sys.source{i}{j}.handle_mesh=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',source{j}.conn,...
                'facecol','none',...
                'edgecolor',meshcolor,...
                'marker','.',...
                'tag',tag,...
                'visible','off');
        end        
        if sourcetype==3
            gpsm = xyz2gps(source{j}.xyzm, ae);
            sys.source{i}{j}.handle_mesh=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',source{j}.conn,...
                'facecol','none',...
                'edgecolor',meshcolor,...
                'tag',tag,...
                'visible','off');
        end        
        if sourcetype==4
            sys.source{i}{j}.handle_mesh=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',source{j}.conn,...
                'facecol','none',...
                'edgecolor',meshcolor,...
                'tag',tag,...
                'visible','off');
        end        
        if sourcetype==5
            t  = source{j}.conn;
            t2 = [t(:,[1 2 3]);t(:,[1 4 3]);t(:,[2 3 4]);t(:,[1 2 4])];
            t2 = unique(sort(t2,2),'rows');
            gpsm = xyz2gps(source{j}.xyzm, ae);
            
            sys.source{i}{j}.handle_mesh=patch('parent',ax3,...
                'vertices',gpsm(:,1:2),...
                'faces',t2,...
                'facecolor','none',...
                'edgecolor',meshcolor,...
                'tag',tag,...
                'visible','off');
            
        end
    end
    
    %% source edge
    tag = sprintf('edge%g' ,i);
    for j=indsource
        sourcetype=round(source{j}.sourcetype);
        if sourcetype==1
            sys.source{i}{j}.handle_edge=plot(ax3,source{j}.vert(1),source{j}.vert(2),'ks',...
                'markersize',4,...
                'markerfacecolor',edgecolor,...
                'tag',tag,...
                'visible','off');
        end
        
        if sourcetype==2
            sys.source{i}{j}.handle_edge=plot(ax3,source{j}.vert(:,1),source{j}.vert(:,2),...
                'color',edgecolor,...
                'tag',tag,...
                'linewidth',1,...
                'visible','off');
        end
        
        if sourcetype==3
            sys.source{i}{j}.handle_edge=plot(ax3,source{j}.vert(:,1),source{j}.vert(:,2),...
                'color',edgecolor,...
                'tag',tag,...
                'visible','off');
        end
        
        if sourcetype==4
            sys.source{i}{j}.handle_edge=plot(ax3,source{j}.vert(:,1),source{j}.vert(:,2),...
                'color',edgecolor,...
                'tag',tag,...
                'visible','off');
        end
        
        if sourcetype==5
            sys.source{i}{j}.handle_edge=plot(ax3,source{j}.vert(:,1),source{j}.vert(:,2),...
                'color',edgecolor,...
                'tag',tag,...
                'visible','off');
        end
    end
    
    %% source labels
    tag    = sprintf('sourcelabel%g',i);
    labelG = strrep(sys.labelG{i},'_','-');
    for j=indsource
        sourcetype=round(source{j}.sourcetype);
        if sourcetype==1
            cm=source{j}.vert;
        else
            cm=source{j}.center;
        end
        sys.source{i}{j}.handle_txt=text(ax3,cm(1),cm(2),labelG{j},'fontsize',8,'fontweight','bold','visible','off','tag',tag,'horizontalalignment','center','verticalalignment','bottom');
    end
end


