function newmscl=sh_updateMscl(handles)

switch handles.P5_formulation.Value
    case 1 % delta
        num=[...
            handles.P5_e1.Value...
            str2double(handles.P5_e2.String)];
        
    case 2 % truncexp
        num=[...
            handles.P5_e1.Value...
            str2double(handles.P5_e2.String)...
            str2double(handles.P5_e3.String)...
            str2double(handles.P5_e4.String)...
            str2double(handles.P5_e5.String)];
        
    case 3 % truncnorm
                num=[...
            handles.P5_e1.Value...
            str2double(handles.P5_e2.String)...
            str2double(handles.P5_e3.String)...
            str2double(handles.P5_e4.String)...
            str2double(handles.P5_e5.String)...
            str2double(handles.P5_e6.String)];
        
    case 4 % yc1985
                num=[...
            handles.P5_e1.Value...
            str2double(handles.P5_e2.String)...
            str2double(handles.P5_e3.String)...
            str2double(handles.P5_e4.String)...
            str2double(handles.P5_e5.String)];
        
end
labelG=vertcat(handles.sys.labelG{:});
newmscl.type    = handles.P5_formulation.Value;
newmscl.source  = labelG{handles.P5_list.Value};
newmscl.adp     = [];
newmscl.num     = num;
newmscl.mptr    = [];
newmscl.mdata   = [];
newmscl.meanMo  = [];